tweaks

diff --git a/.github/workflows/docker-compose-validation.yml b/.github/workflows/docker-compose-validation.yml
--- a/.github/workflows/docker-compose-validation.yml
+++ b/.github/workflows/docker-compose-validation.yml
@@ -34,6 +34,11 @@ jobs:
             else
               echo "ERROR"
               echo "$config_check"
-              exit 1
+              error=true
             fi
           done
+
+          if $error; then
+            echo "One or more docker-compose.yml files have errors. Please fix them."
+            exit 1
+          fi
